export const TOOLBAR_ITEMS = [
  { label: "{{…}}", insert: "{{}}",          cursorBack: 2, title: "穴埋め" },
  { label: "$…$",   insert: "$$",              cursorBack: 1, title: "インライン数式" },
  { label: "$$…$$", insert: "$$$$",            cursorBack: 2, title: "ブロック数式" },
  { label: "a/b",   insert: "\\frac{}{}",      cursorBack: 1, title: "分数" },
  { label: "√",     insert: "\\sqrt{}",        cursorBack: 1, title: "平方根" },
  { label: "xⁿ",    insert: "^{}",             cursorBack: 1, title: "指数" },
  { label: "xₙ",    insert: "_{}",             cursorBack: 1, title: "添字" },
  { label: "Σ",     insert: "\\sum_{i=1}^{n}", cursorBack: 0, title: "シグマ" },
  { label: "∫",     insert: "\\int_{}^{}",     cursorBack: 4, title: "積分" },
  { label: "π",     insert: "\\pi ",           cursorBack: 0, title: "π" },
  { label: "α",     insert: "\\alpha ",        cursorBack: 0, title: "α" },
  { label: "β",     insert: "\\beta ",         cursorBack: 0, title: "β" },
  { label: "θ",     insert: "\\theta ",        cursorBack: 0, title: "θ" },
  { label: "∞",     insert: "\\infty ",        cursorBack: 0, title: "∞" },
  { label: "±",     insert: "\\pm ",           cursorBack: 0, title: "±" },
  { label: "×",     insert: "\\times ",        cursorBack: 0, title: "×" },
  { label: "≤",     insert: "\\leq ",          cursorBack: 0, title: "≤" },
  { label: "≥",     insert: "\\geq ",          cursorBack: 0, title: "≥" },
];
